### ISSUE TITLE
Finding a real data set

### ISSUE THREAD

**Issue by matthewrw** [matthewrw/Sieves_Project#2]
Yesterday we talked about the Mauna Loa and presidents data set.

I found a list of data sets in different R packages here: https://vincentarelbundock.github.io/Rdatasets/datasets.html

Do either of you recognize any of these data sets as candidates to use. I've looked at the NOxEmissions data set but there's not a very strong trend to easily model

**Comment by njosephs** [comment]
We simulated $N = 150$ data points from the model

\begin{center}

$Y = \sin^3(2\pi X^3) + \epsilon$

\end{center}


where


\begin{center}

$X \sim N(0,1)$

\end{center}


and


\begin{center}

$\epsilon \sim N(0, .2)$

\end{center}


with the goal of fitting a polynomial series estimator to the data. From $n = 10$ to $N$ in increments of $10$, we fit such models with degrees of complexity varying from $1$ to $8$. We repeated this on $200$ separate datasets and plotted the PSE against $n$. The results are below. As expected, the PSE decreases as $n$ increases. Furthermore, the optimal degree increases with $n$. A linear model is best only for $n=10$. At $n=20$, a quadratic fit minimizes the PSE. However, by $n=30$ a fifth degree polynomial is best and remains so until $n=50$. Ultimately, a sixth degree polynomial performs very well and is not supplanted by a seventh degree polynomial until $n=90$. We note that an eighth degree polynomial never minimizes the PSE.



________________________________
